export const MOCK_DATA = [
    {
        id: 1,
        projectName: 'App Launch',
        elements: [
            {
                elementId: 'element01',
                elementName: 'Dialog',
                arrayCondition: [
                    {
                        condition01Id: 'condition01',
                        condition01Name: 'condition name 1',
                        dataCondition01: [
                            {
                                condition02Id: 'condition_id_02',
                                condition02Name: 'condition name 02',
                                dataCondition02: [
                                    {
                                        condition03Id: 'condition id 03',
                                        condition03Name: 'condition name 03',
                                        testcase: [
                                            {
                                                testcaseId: 'data01',
                                                dataConditionName: 'data1',
                                                tester: 'tester01',
                                                dev: 'dev01',
                                                result: 'OK',
                                                system: 'Normal',
                                                dateTested: '2021/10/25',
                                                evidenceNo: '007',
                                                retest: 'OK',
                                                level: 'simple',
                                            },
                                            {
                                                testcaseId: 'data02',
                                                dataConditionName: 'data2',
                                                tester: 'tester02',
                                                dev: 'dev02',
                                                result: 'OK',
                                                system: 'Normal',
                                                level: 'simple',
                                                dateTested: '2021/10/25',
                                                retest: 'NG',
                                            },
                                            {
                                                testcaseId: 'data03',
                                                dataConditionName: 'data3',
                                                tester: 'tester03',
                                                dev: 'dev03',
                                                result: 'OK',
                                                system: 'Abnormal',
                                                level: 'advanced',
                                                dateTested: '2021/10/25',
                                                retest: 'NG',
                                            },
                                        ],
                                    },
                                    {
                                        condition03Id: 'condition id 0312',
                                        condition03Name: 'condition name 03 21312',
                                        testcase: [
                                            {
                                                testcaseId: 'data07',
                                                dataConditionName: 'data1',
                                                tester: 'tester01',
                                                dev: 'dev01',
                                                result: 'OK',
                                                system: 'Normal',
                                                dateTested: '2021/10/25',
                                                evidenceNo: '007',
                                                retest: 'OK',
                                                level: 'simple',
                                            },
                                            {
                                                testcaseId: 'data08',
                                                dataConditionName: 'data2',
                                                tester: 'tester02',
                                                dev: 'dev02',
                                                result: 'OK',
                                                system: 'Normal',
                                                level: 'simple',
                                                dateTested: '2021/10/25',
                                                retest: 'NG',
                                            },
                                            {
                                                testcaseId: 'data09',
                                                dataConditionName: 'data3',
                                                tester: 'tester03',
                                                dev: 'dev03',
                                                result: 'OK',
                                                system: 'Abnormal',
                                                level: 'advanced',
                                                dateTested: '2021/10/25',
                                                retest: 'NG',
                                            },
                                        ],
                                    },
                                ],
                            },
                            {
                                condition02Id: 'condition_id_02 01',
                                condition02Name: 'condition name 02 01',
                                dataCondition02: [
                                    {
                                        condition03Id: 'condition id 03 01',
                                        condition03Name: 'condition name 03 01',
                                        testcase: [
                                            {
                                                testcaseId: 'data04',
                                                dataConditionName: 'data4',
                                                tester: 'tester04',
                                                dev: 'dev04',
                                                result: 'OK',
                                                system: 'Normal',
                                                level: 'simple',
                                                dateTested: '2021/10/25',
                                                retest: 'NG',
                                            },
                                            {
                                                testcaseId: 'data05',
                                                dataConditionName: 'data5',
                                                tester: 'tester05',
                                                dev: 'dev05',
                                                result: 'OK',
                                                system: 'Abnormal',
                                                level: 'simple',
                                                dateTested: '2021/10/24',
                                                retest: 'NG',
                                            },
                                            {
                                                testcaseId: 'data06',
                                                dataConditionName: 'data6',
                                                tester: 'tester06',
                                                dev: 'dev06',
                                                result: 'OK',
                                                level: 'advanced',
                                                system: 'Normal',
                                                dateTested: '2021/10/24',
                                                retest: 'NG',
                                            },
                                        ],
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        condition01Id: 'condition01 01',
                        condition01Name: 'condition name 1213',
                        dataCondition01: [
                            {
                                condition02Id: 'condition_id_02 21321321',
                                condition02Name: 'condition name 0221321312',
                                dataCondition02: [
                                    {
                                        condition03Id: 'condition id 0321333',
                                        condition03Name: 'condition name 03',
                                        testcase: [
                                            {
                                                testcaseId: 'data10',
                                                dataConditionName: 'data1',
                                                tester: 'tester01',
                                                dev: 'dev01',
                                                result: 'OK',
                                                system: 'Normal',
                                                level: 'simple',
                                                dateTested: '2021/10/25',
                                                evidenceNo: '007',
                                                retest: 'OK',
                                            },
                                        ],
                                    },
                                    {
                                        condition03Id: 'condition id 03122',
                                        condition03Name: 'condition name 03 213121',
                                        testcase: [
                                            {
                                                testcaseId: 'data11',
                                                dataConditionName: 'data1',
                                                tester: 'tester01',
                                                dev: 'dev01',
                                                level: 'simple',
                                                result: 'OK',
                                                system: 'Normal',
                                                dateTested: '2021/10/25',
                                                evidenceNo: '007',
                                                retest: 'OK',
                                            },
                                            {
                                                testcaseId: 'data12',
                                                dataConditionName: 'data2',
                                                tester: 'tester02',
                                                dev: 'dev02',
                                                result: 'OK',
                                                system: 'Normal',
                                                level: 'simple',
                                                dateTested: '2021/10/25',
                                                retest: 'NG',
                                            },
                                        ],
                                    },
                                ],
                            },
                            {
                                condition02Id: 'condition_id_02 0122',
                                condition02Name: 'condition name 02 01222',
                                dataCondition02: [
                                    {
                                        condition03Id: 'condition id 03 012222',
                                        condition03Name: 'condition name 03 012222222',
                                        testcase: [
                                            {
                                                testcaseId: 'data13',
                                                dataConditionName: 'data4',
                                                tester: 'tester04',
                                                dev: 'dev04',
                                                result: 'OK',
                                                system: 'Normal',
                                                level: 'simple',
                                                dateTested: '2021/10/25',
                                                retest: 'NG',
                                            },
                                            {
                                                testcaseId: 'data14',
                                                dataConditionName: 'data5',
                                                tester: 'tester05',
                                                dev: 'dev05',
                                                result: 'OK',
                                                system: 'Abnormal',
                                                level: 'simple',
                                                dateTested: '2021/10/24',
                                                retest: 'NG',
                                            },
                                            {
                                                testcaseId: 'data15',
                                                dataConditionName: 'data6',
                                                tester: 'tester06',
                                                dev: 'dev06',
                                                result: 'OK',
                                                level: 'advanced',
                                                system: 'Normal',
                                                dateTested: '2021/10/24',
                                                retest: 'NG',
                                            },
                                            {
                                                testcaseId: 'data16',
                                                dataConditionName: 'data6',
                                                tester: 'tester06',
                                                dev: 'dev06',
                                                result: 'OK',
                                                level: 'advanced',
                                                system: 'Normal',
                                                dateTested: '2021/10/24',
                                                retest: 'NG',
                                            },
                                        ],
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
    },
];
